version: '3.8'

services: 
  localai:       
    # image: localai/localai:latest-aio-gpu-hipblas
    image: pr2196:latest
    deploy:
      resources:
        limits:
          cpus: 8.0
          memory: 32G        
    environment:      
      - DEBUG=true    
      # - REBUILD=true
      - BUILD_TYPE=hipblas
      # - BUILD_GRPC_FOR_BACKEND_LLAMA=ON      
      - GPU_TARGETS=gfx1100
      # - HSA_OVERRIDE_GFX_VERSION=10.3.0
      - HSA_OVERRIDE_GFX_VERSION=11.0.0
      #- CMAKE_BUILD_PARALLEL_LEVEL=8
      #- MAKEFLAGS=-j8 -Otarget
      - HIP_VISIBLE_DEVICES=0 
    ports:
      - "8080:8080"
    volumes:
      - ./models:/build/models:cached
    devices:          
      - /dev/dri
      - /dev/kfd
    security_opt:
      - seccomp:unconfined